#!/usr/bin/env ansible-playbook
---

- name: Adds user to group (default ssh)
  hosts: all
  gather_facts: False

  tasks:

    - { meta: noop, vars: { macros: &loo { delegate_to: localhost, run_once: True }}}
    - { assert: { that: 'groups.all | difference(play_hosts) != []' }, <<: *loo, name: Assert hosts subset }
    - { assert: { that: user is defined }, <<: *loo, name: Assert user }

    - set_fact: { group: '{{ group | default("ssh")}}' }
      name: Default group to ssh

    - set_fact: { debug: '{{ debug | default(False) }}' }
      name: Default debug to False

    - getent: { database: group, key: '{{ group }}' }
      name: Get users already in group

    - set_fact: { missing: '{{ [ user ] | difference(getent_group[group][2].split(",")) }}' }
      name: Find if user not yet in group

    - { debug: { var: missing }, when: debug }

    - user:
        name: '{{ item }}'
        groups: '{{ group }}'
        append: True
      loop: '{{ missing }}'
      become: True
      name: Adds group {{ group }} to user {{ missing | join('') }}
