---

#- hosts: epiconcept.net
- hosts: rebond2:debian-build2:misc
  gather_facts: False
  run_once: True
  tasks:
    - set_fact: { Hosts: '{{ play_hosts | sort }}' }
      delegate_to: localhost
      delegate_facts: True
