#!/usr/bin/env ansible-playbook
---

- import_playbook: asserts.yml
  when: False

- name: Generate an user password
  hosts: localhost
  gather_facts: True

  vars_files: [ paths.yml ]

  tasks:

    - meta: noop
      vars:
        macros:
          - &ro
            changed_when: False
            check_mode: False
          - &pass
            PASSWORD_STORE_GIT: '{{ password_store }}'
            PASSWORD_STORE_DIR: '{{ password_store_dir }}'

    - include_vars: { file: epi_user.json, name: epi }
      name: Include users data

    - assert: { that: 'trigram is defined and epi.users.trigram[trigram] is defined' }
      name: Check args

    - set_fact: { user: '{{ epi.users.trigram[trigram] }}' }
      name: Get user data

    - stat: { path: '{{ password_store_dir + "/users/linux/" + trigram + ".gpg" }}' }
      register: st
      name: Stat user password file

    - block:

      - command:
        args:
          argv: [ makepasswd, '--crypt-md5' ]
        register: makepasswd
        <<: *ro
        name: Generate password and MD5

      - set_fact: { password: '{{ makepasswd.stdout.split(" ") | select("!=", "") | list }}' }
        name: Separate password and MD5

      - { command: date +%F, register: date, <<: *ro, tags: always, name: Get date }

      - command:
        args:
          argv: '{{ pass_cmd  + [ pass_name ] }}'
          stdin: |
            {{ passw }}
            md5: {{ md5 }}
            login: {{ login }}
            name: {{ name }}
            date: {{ date.stdout }}
        vars:
          pass_cmd: [ pass, insert, -m ]
          pass_name: 'users/linux/{{ trigram }}'
          login: '{{ user.login }}'
          name:  '{{ user.name }}'
          mail:  '{{ user.mail }}'
          passw: '{{ password[0] }}'
          md5:   '{{ password[1] }}'
        environment: { <<: *pass }
        name: Store password and MD5 using pass

      - command: pass git push
        environment: { <<: *pass }
        name: Push new GPG password file using pass git

      when: st.stat.exists == False

    - meta: end_play
