#!/usr/bin/env ansible-playbook
---

- { import_playbook: play_on_oxa.yml }
- { import_playbook: asserts.yml, when: assert is defined }

- name: Setup user keys
  hosts: '{{ hostvars.localhost.Hosts }}'
  gather_facts: False
  vars_files: [ paths.yml ]
  tasks:

    - { meta: noop, vars: { macros: &ro { changed_when: False, check_mode: False }}}

    - include_tasks: include/user-get.yml

    - command: getent passwd {{ login }}
      register: getent
      <<: *ro
      failed_when: getent.rc == 1 or getent.rc == 3
      name: User existp

    - include_tasks: include/user-set-keys.yml
      when: getent.stdout_lines | count
