#!/usr/bin/env ansible-playbook
---

- { import_playbook: play_on_oxa.yml }
- { import_playbook: play_on_char.yml, when: char is defined }
- { import_playbook: play_on_epi.yml, when: epi is defined }
- { import_playbook: asserts.yml, when: assert is defined }

- name: Create user
  hosts: '{{ hostvars.localhost.Hosts }}'
  gather_facts: False
  vars_files: [ paths.yml ]
  vars:
    sudosh: /usr/local/bin/sudosh
    bash: /bin/bash
  tasks:

    - include_tasks: include/user-get.yml
    - include_tasks: include/user-get-password.yml

    - stat: { path: '{{ sudosh }}' }
      register: st
      name: See if sudosh installed

    - set_fact: { shell: '{{ sudosh if st.stat.exists else bash }}' }
      name: Choose login shell

    - user:
        name: '{{ login }}'
        password: '{{ md5 }}'
        comment: '{{ name }}'
        update_password: '{{ update_password | default("on_create") }}'
        shell: '{{ shell }}'
      become: True
      name: Create user

    - { meta: noop, vars: { macros: &ro { changed_when: False, check_mode: False }}}

    - command: getent passwd {{ login }}
      register: getent
      failed_when: getent.rc == 1 or getent.rc == 3
      <<: *ro
      name: Existp user 

    - include_tasks: include/user-set-keys.yml
      when: getent.stdout_lines | count

    - meta: end_play
