#!/usr/bin/env ansible-playbook
---

- { import_playbook: asserts.yml, when: assert is defined, vars: { Hosts: localhost }}

- name: Generate an user password
  hosts: localhost
  gather_facts: True

  vars: { pass_subdir: '{{ "users/" + ("alien/" + set if set is defined else "linux") }}' }
  vars_files: [ '{{ "paths" + ("-" + set if set is defined else "") + ".yml" }}' ]

  tasks:

    - meta: noop
      vars:
        macros:
          - &ro
            changed_when: False
            check_mode: False
          - &pass
            PASSWORD_STORE_GIT: '{{ password_store }}'
            PASSWORD_STORE_DIR: '{{ password_store_dir }}'

    - include_tasks: include/user-get.yml

    - stat: { path: '{{ password_store_dir + "/users/linux/" + trigram + ".gpg" }}' }
      register: st
      name: Stat user password file

    - when: st.stat.exists == False or force is defined
      name: Creation block
      block:

      - command:
        args:
          argv: [ makepasswd, '--crypt-md5' ]
        register: makepasswd
        <<: *ro
        name: Generate password and MD5

      - set_fact: { password: '{{ makepasswd.stdout.split(" ") | select("!=", "") | list }}' }
        name: Separate password and MD5

      - { command: date +%F, register: date, <<: *ro, tags: always, name: Get date }

      - command:
        args:
          argv: '{{ pass_cmd  + [ pass_name ] }}'
          stdin: |
            {{ passw }}
            md5: {{ md5 }}
            login: {{ login }}
            name: {{ name }}
            date: {{ date.stdout }}
        vars:
          pass_cmd: [ pass, insert, -m ]
          pass_name: '{{ pass_subdir + "/" + trigram }}'
          login: '{{ user.login }}'
          name:  '{{ user.name }}'
          mail:  '{{ user.mail }}'
          passw: '{{ password[0] }}'
          md5:   '{{ password[1] }}'
        environment: { <<: *pass }
        name: Store password and MD5 using pass

      - command: pass git push
        environment: { <<: *pass }
        name: Push new GPG password file using pass git

    - meta: end_play
